server:
  port: 8080

grpc:
  server:
    port: 59091
    enableKeepAlive: true
    keepAliveWithoutCalls: true
    negotiationType: plaintext

spring:
  application:
    name: collector

# Новые настройки Kafka для Collector
collector:
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: ru.yandex.practicum.collector.serialization.AvroSerializer
      acks: all
      retries: 3